build_from:
  aarch64: ghcr.io/home-assistant/aarch64-homeassistant:latest
  amd64: ghcr.io/home-assistant/amd64-homeassistant:latest
  armhf: ghcr.io/home-assistant/armhf-homeassistant:latest
  armv7: ghcr.io/home-assistant/armv7-homeassistant:latest
